version: '3.6'
services:
    redis:
        image: redis/redis-stack
        ports:
            - '6379:6379'
            - '8001:8001'
        volumes:
            - redis-data:/data
        restart: always

networks:
    default:
        name: dev

volumes:
    redis-data:
